### PR TITLE
Improvement to REST client

### PR DESCRIPTION
**Pull request by pdudits**
Thanks for implementing my previous suggestions I'd want to help you directly with final one :)

This adds the artifact to BOM, and removes artificial qualifier from CDI extension - I added one more test to TCK (I'll submit that later) to verify that things are injected properly with various combinations of `@RegisterRestClient` and `@RestClient` being present or not present.

### CODE REVIEW

**Comment by pdudits** [comment]
Few more commits are coming...

**Comment by Verdent** [comment]
Thank you. These changes looks good :-)

**Comment by Verdent** [comment]
Your changes don't have required sign off in all of your commits. Please could you fix that and create new PR? I will revert your changes for now.

**Comment by pdudits** [comment]
Sure. New PR will follow shortly.

**Pull request merged**
